### ISSUE TITLE
Extension fails to activate.

### ISSUE THREAD

**Issue by bddenhartog** [josa42/vscode-markdown-table-formatter#4] opened 2017-05-21 23:55 UTC
Steps to reproduce:

- Install VSCode

- Execute `code --install-extension josa.markdown-table-formatter`

- Open VSCode

- Click `Help -> Toggle Developer Tools`

Output:

```javascript
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 
[Extension Host] Activating extension `josa.markdown-table-formatter` failed: Cannot find module 'reformat-markdown-table'.
d.logExtensionHostMessage @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29

//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 
[Extension Host] Activating extension `josa.markdown-table-formatter` failed:  Cannot find module 'reformat-markdown-table'
d.logExtensionHostMessage @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29

//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 
[Extension Host] Here is the error stack:  Error: Cannot find module 'reformat-markdown-table'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366378)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/USERNAME/.vscode/extensions/josa.markdown-table-formatter-0.2.0/out/src/extension.js:7:35)
    at Object.<anonymous> (/home/USERNAME/.vscode/extensions/josa.markdown-table-formatter-0.2.0/out/src/extension.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Y.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366378)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.s [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:4:25886)
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Activating extension `josa.markdown-table-formatter` failed: Cannot find module 'reformat-markdown-table'.
t.$localShowMessage @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```
I took a look at your `package.json`; it looks like the module `reformat-markdown-table` is in the `devDependencies` object. I haven't developed a vscode extension at all -- is this accurate, or would moving it to the `dependencies` object be a better choice?

**Comment by r0f3n** [comment] 2017-05-22 20:36
It requires extension "Table Formatter", which is better anyway.

**Comment by josa42** [comment] 2017-05-23 11:28
The issue is fixed in the latest release. Thanks for reporting!

**Closed by josa42** 2017-05-23 11:28 UTC
