### ISSUE TITLE
How do I get it working?

### ISSUE THREAD

**Issue by john-doherty** [josa42/vscode-markdown-table-formatter#2] opened 2017-03-03 14:24 UTC
I've installed the plugin, selected a markdown table and tried the key combo but it just deletes the text and leave a character behind. How do I confirm this plugin is running?

**Comment by josa42** [comment] 2017-05-23 11:28
The issue is fixed in the latest release. Thanks for reporting!

**Closed by josa42** 2017-05-23 11:28 UTC
